package by.epam.litvinko.beautysalon.controller.command;

public enum CommandType {
    SIGN_IN,
    SIGN_UP,
    LOG_OUT,
    CHANGE_LOCALE,
    FORGOT_PASSWORD,
    EDIT_PASSWORD,
    EDIT_PROFILE,
    EDIT_PHOTO,
    PRODUCT_DETAIL,
    REMOVE_PRODUCT,
    CREATED_ORDER,
    ADD_TO_CART,
    ADD_COUPON,
    GO_TO_MAIN_PAGE,
    GO_TO_PROFILE_PAGE,
    GO_TO_SHOP_PAGE,
    GO_TO_EDIT_PASSWORD_PAGE,
    GO_TO_EDIT_PROFILE_PAGE,
    GO_TO_FORGOT_PASSWORD_PAGE,
    GO_TO_SIGNUP_PAGE,
    GO_TO_CART_PAGE,
    DEFAULT
}
